name: Run index.js every 7 days

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 0 * * 1' # 每周一执行一次，每天的 00:00

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: 迁出代码
              uses: actions/checkout@v4

            - name: 设置nodejs环境
              uses: actions/setup-node@v3
              with:
                  node-version: 20 # 可以根据需要选择合适的 Node.js 版本

            - name: 运行index.js
              env:
                  Authorization: ${{ secrets.Authorization }}
                  TEST: ${{ secrets.TEST }}
              run: node index.js
